# Tracking data: Introduction

<!--- This is an HTML comment in RMarkdown. You can use these comments to make notes that won't get read when running the code -->

<!--- If you don't understand what a RMarkdown document is. Stop here. Go learn. -->

<!--- Equally. You must understand the difference between Markdown vs. RMarkdown -->

<!--- Remember, outside of the R code chunks we are now coding in HTML syntax, not R syntax -->

This chapter was built with **`r sessionInfo()$R.version$version.string`**\

The chapter was last updated on **`r Sys.Date()`** <br>

<!--- In the code chunk below, we specify include = F, so that we will run the chunk but not include the chunk in the final document. We set a global argument in the code chunk of echo = T, so that in later code chunks, the code will be displayed in the RMarkdown document -->

```{r track-intro-setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
## we also specify in the options here to set the overall working directory
## back to the root directory of the R Project we are working in. We do this
## because by default , the working directory for R code chunks is the directory 
## that contains the Rmd document. We don't want this option given our file
## set up prefers the option of having the working directory specified as that
## where the R Project is.
knitr::opts_knit$set(root.dir = "..")
```

## Introduction to animal tracking data considered in this toolkit

This toolkit focuses on the analysis of data primarily from GPS and PTT devices. Some of the analyses may be extended to data from GLS devices. For all devices, we encourage users to understand the limitations of each device and how these limitations can affect interpretation of animal movement patterns.

For a general introduction into understanding **animal movement patterns**, we refer users to:

- **animal movement references TBC**

For a general introduction into understanding **seabird movement patterns**, we refer users to:

- **seabird movement references TBC**

For a general introduction into understanding **GPS, PTT and GLS technologies**, we refer users to:

- **GPS, PTT, GLS references TBC**

## Lay introduction to GPS, PTT, GLS devices

[Consider from MIRO board: Figure: Location data associated with different device types: GPS | PTT | GLS. Showcasing error associated with devices.

Also: consider general text about accuracy of each device and pros and cons of using different devices.]
